[profile.default]
src = 'src'
out = 'out'
libs = ['../node_modules']
solc = '0.8.20'
optimizer = true
optimizer_runs = 200
evm_version = "cancun"    

remappings = [ 
  '@openzeppelin/=../node_modules/@openzeppelin/',
  'forge-std/=lib/forge-std/src/',
]
fs_permissions = [
    { access = 'read-write', path = './foundry-cache' },
]

[rpc_endpoints]
arbitrum = 'https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}'
optimism = 'https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}'
ethereum = 'https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
